WITH CTE AS (

    select
    START_TIME
    from {{ source('demo', 'bike') }} 
)
,

CTE_TIME AS (

select
START_TIME,
DATE(START_TIME) AS START_DATE,
HOUR(START_TIME) AS START_HOUR,

CASE WHEN DAYNAME(START_TIME) IN ('Sat','Sun')
    THEN 'WEEKEND'
    ELSE 'BUDINESSDAY'
    END AS DAY_TYPE,

CASE WHEN MONTH(START_TIME) in (12,1,2)
THEN 'WINTER'
WHEN MONTH(START_TIME) in (3,4,5)
THEN 'SPRING'
WHEN MONTH(START_TIME) in (6,7,8)
THEN 'SUMMER'
ELSE 'AUTUMN'
END AS STATION_OF_YEAR

from CTE
)

select
*
from CTE_TIME
